# Nuclear Alpaca Configuration file
# Author: Nexty6
# Date: 26/08/20

debug: true                     # Turn this one if you'd like to get a lot of information in the console + in-game. (for developpers)

holo-display-time: 10           # How long an Alpaca's Hologram stays active after an interaction (in seconds)

alpaca-behavior:
    starting-hunger: 72.0       # The initial hunger of an Alpaca (in %, more means less hungry)
    starting-happiness: 48.0    # The initial happiness of an Alpaca (in %, more means happier)
    starting-readiness: 12.0    # The initial readiness of an Alpaca (in %, more means closer to being able to get its wool harvested)
    starting-quality: 0.0       # The initial wool quality of an Alpaca (in %, more means better quality)

    alone-factor: -6.0          # Value subtracted from an Alpaca's Happiness in case there are NO other Alpacas nearby. (per hour)
    family-factor: 0.6          # Value added to an Alpaca's Happiness in case there ARE other Alpacas nearby. (per nearby Alpaca, per hour)
    hunger-factor: 1.5          # TODO
    music-factor: 0.6           # TODO

    happiness-factor: 0.6       # TODO
    prev-happiness-factor: 0.3  # TODO

    readiness-factor: 25.0      # TODO

    min-hunger-value: 0.6       # Minimum hunger an Alpaca loses (per hour, inclusive)
    max-hunger-value: 1.0       # Maximum hunger an Alpaca loses (per hour, exclusive)
    feed-delay: 8.0             # Cooldown between feeding an Alpaca (in hours)
    feed-amount: 12.0           # Maximum amount an Alpaca can eat before activating the feed-delay
    food:                       # Materials that can be eaten by an Alpaca, followed by their hunger value
        - APPLE 5.0
        - CARROT 2.0
        - GRASS 0.5