# Nuclear Alpaca Configuration file
# Author: Nexty6
# Date: 26/08/20

alpaca-behavior:
    alone-factor: -1.0          # TODO
    family-factor: 0.1          # TODO
    hunger-factor: 0.25         # TODO
    music-factor: 0.1           # TODO

    feed-delay: 8.0             # Cooldown between feeding an Alpaca (in hours)
    feed-amount: 12.0           # Maximum amount an Alpaca can eat before activating the feed-delay
    food:                       # Materials that can be eaten by an Alpaca, followed by their hunger value
        - APPLE 5.0
        - CARROT 2.0
        - GRASS 0.5